### PR TITLE
Dev2

### PR DESCRIPTION
**Pull request by krebbi**
Support for Multiple Domains per Serverpilot-APP

Now the script iterates through the nginx-config and gets all domains. 
then there's a request for all the domains in the cert. 
so now it works with "https://www.domain.com" and "https://domain.com" automatically.

### CODE REVIEW

**Comment by dfinnema** [comment]
Some great changes here, just wondering though would this not restrict the generation / renewal of an SNI SSL cert with multiple apps on one server?

**Comment by krebbi** [comment]
I run multiple apps with multiple domains per app and it works just fine right now. 
renewal isn't testet right now, but maybe you could check this with the test-env of let's encrypt?

**Comment by dfinnema** [comment]
I have just added SNI and CRON JOB support for multiple apps in the development branch. Just wondering if you can have a look to see if we can maybe merge your code partially with this branch.

**Comment by krebbi** [comment]
I don't know if it's necessary to have SNI for all Apps. Beside the fact that this would generate a huge Cert, creating one Cert for several domains works and doesn't throw any errors in the most common browsers. 
have a look at https://www.copter.film/ and the links there. all domains linked are running in the same App and do have therefore the same cert.

**Comment by dfinnema** [comment]
The reason why I enabled that option is because there can only be one cert per IP so this would allow multiple apps on one server to use SSL by use of SNI. it doesn't automatically add all the SNI's from all apps but a user can add it should they wish to though. Your implementation works well but would limit to only one app on the server to use SSL with no other apps to use it.

**Comment by krebbi** [comment]
i tested it now with 9 certs (apps) with 33 Domains on one IP. Works perfectly.

**Comment by Remo** [comment]
@dfinnema not sure I understand your concerns about multiple apps, but I'd be happy to test this and the cronjob both together. Let me know if I can be of any assistance with this issue.

**Comment by krebbi** [comment]
Hi @Remo , do you want to dig into this?

**Comment by Remo** [comment]
@krebbi I'd like to know if there's a technical problem before spending any time on this. I don't know much about SNi myself..

**Comment by krebbi** [comment]
@dfinnema I just did a little research and you can have several SNI-certs per IP. Only with WinXP & IE8 you'll have problems, but let's encrypt certs do have problems with IE8 anyways. 
so now just the renewal thing via cron is missing.

**Pull request closed without merging**
